// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_tailor from "./routes/admin/tailor.tsx";
import * as $api_cv_export from "./routes/api/cv/export.ts";
import * as $api_cv_export_slug_ from "./routes/api/cv/export/[slug].ts";
import * as $api_cv_export_cover_letter_slug_ from "./routes/api/cv/export/cover-letter/[slug].ts";
import * as $api_cv_tailor from "./routes/api/cv/tailor.ts";
import * as $api_ical_year_ from "./routes/api/ical/[year].ts";
import * as $api_ical_index from "./routes/api/ical/index.ts";
import * as $api_profile from "./routes/api/profile.ts";
import * as $calendar from "./routes/calendar.tsx";
import * as $cv_slug_ from "./routes/cv/[slug].tsx";
import * as $index from "./routes/index.tsx";
import * as $CopyCoverLetter from "./islands/CopyCoverLetter.tsx";
import * as $CopyFeedUrl from "./islands/CopyFeedUrl.tsx";
import * as $CoverLetterSavePdf from "./islands/CoverLetterSavePdf.tsx";
import * as $CvActions from "./islands/CvActions.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $TailorCvForm from "./islands/TailorCvForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/tailor.tsx": $admin_tailor,
    "./routes/api/cv/export.ts": $api_cv_export,
    "./routes/api/cv/export/[slug].ts": $api_cv_export_slug_,
    "./routes/api/cv/export/cover-letter/[slug].ts":
      $api_cv_export_cover_letter_slug_,
    "./routes/api/cv/tailor.ts": $api_cv_tailor,
    "./routes/api/ical/[year].ts": $api_ical_year_,
    "./routes/api/ical/index.ts": $api_ical_index,
    "./routes/api/profile.ts": $api_profile,
    "./routes/calendar.tsx": $calendar,
    "./routes/cv/[slug].tsx": $cv_slug_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CopyCoverLetter.tsx": $CopyCoverLetter,
    "./islands/CopyFeedUrl.tsx": $CopyFeedUrl,
    "./islands/CoverLetterSavePdf.tsx": $CoverLetterSavePdf,
    "./islands/CvActions.tsx": $CvActions,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/TailorCvForm.tsx": $TailorCvForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
