// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_ical_year_ from "./routes/api/ical/[year].ts";
import * as $api_ical_index from "./routes/api/ical/index.ts";
import * as $api_profile from "./routes/api/profile.ts";
import * as $calendar from "./routes/calendar.tsx";
import * as $index from "./routes/index.tsx";
import * as $CopyFeedUrl from "./islands/CopyFeedUrl.tsx";
import * as $DownloadCv from "./islands/DownloadCv.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/ical/[year].ts": $api_ical_year_,
    "./routes/api/ical/index.ts": $api_ical_index,
    "./routes/api/profile.ts": $api_profile,
    "./routes/calendar.tsx": $calendar,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CopyFeedUrl.tsx": $CopyFeedUrl,
    "./islands/DownloadCv.tsx": $DownloadCv,
    "./islands/Navbar.tsx": $Navbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
