// A job-specific view layered on top of the master profile JSON.
// Generated by `deno task tailor-cv` or edited by hand under data/variants/.

export interface ProfileVariant {
  slug: string;
  label: string;
  target_role?: string;
  target_company?: string;
  created_at?: string;
  job_description?: string;

  summary?: string;
  occupation?: string;

  /** Stable experience ids from the master profile (see profile catalog). */
  experience_ids?: string[];
  experience_descriptions?: Record<string, string>;

  /** Stable project ids from the master profile. */
  project_ids?: string[];
  project_descriptions?: Record<string, string>;

  /** Skill names to include, in display order (matched case-insensitively). */
  skill_names?: string[];
}
