// A job-specific view layered on top of the master profile JSON.
// Generated by `deno task tailor-cv`, POST /api/cv/tailor, or edited by hand.

export interface ProfileVariant {
  slug: string;
  label: string;
  target_role?: string;
  target_company?: string;
  created_at?: string;
  job_description?: string;

  summary?: string;
  occupation?: string;

  /** Stable experience ids from the master profile (see profile catalog). */
  experience_ids?: string[];
  experience_descriptions?: Record<string, string>;

  /** Stable project ids from the master profile. */
  project_ids?: string[];
  project_descriptions?: Record<string, string>;

  /** Technical skill names to include, in display order. */
  skill_names?: string[];

  /** Soft skill / core strength names to include, in display order. */
  soft_skill_names?: string[];

  /** Opening line, e.g. "Dear Hiring Team," */
  cover_letter_salutation?: string;

  /** Cover letter body paragraphs (no salutation or sign-off). */
  cover_letter?: string;
}
